#!/usr/bin/env bash
# Leak Guard — canonical deny-list + checker for Anton's repos.
#
# ONE source of truth, used by three layers:
#   * .git/hooks/pre-push          -> pre-push-leak-guard (symlink to this dir)
#   * .github/workflows/leak-guard.yml -> calls the repo's .github/leak-guard.sh
#   * ad-hoc audits                -> leak-guard.sh history
#
# The in-repo copies are generated by sync-leak-guard.sh; never edit them by
# hand -- edit this file and re-run the sync.
#
# Usage:
#   leak-guard.sh tree [<ref>]            paths tracked at <ref> (default HEAD)
#   leak-guard.sh range <base> <head>     paths ADDED/MODIFIED in base..head
#   leak-guard.sh history                 paths ever added on any ref (audit)
#
# Exit 0 = clean, 1 = hits found, 2 = usage error.
set -uo pipefail

# --- Secrets: never allowed, whatever the repo. --------------------------
SECRET_RE='(^|/)\.env($|\.)|\.env$|(^|/)secrets?\.ya?ml$|\.(pem|key|p12|pfx|jks|keystore|ppk)$|(^|/)id_(rsa|dsa|ecdsa|ed25519)$|(^|/)\.credentials\.json$|(^|/)\.(netrc|git-credentials|pgpass)$|(^|/)backup-key\.txt$|(^|/)service[-_]account.*\.json$'

# --- Internal / auto-generated docs: fine locally, never public. ---------
INTERNAL_RE='(^|/)(superpowers|internal|private)/|(^|/)docs/plans?/|[-_.](plan|spec|design)\.md$|findings[^/]*\.md$|[^/]*findings\.md$|[-_.]assessment[-_.]|\.local\.[^/]+$|(^|/)graphify-out/|(^|/)\.superpowers/'

# --- Exemptions: templates, placeholders, fixtures. ----------------------
ALLOW_RE='/\.gitkeep$|\.(example|sample|template|dist)$|(^|/)(example|sample|template)[-_.]|(^|/)tests?/fixtures?/'

# --- Scope: which classes are enforced in THIS repo. ---------------------
# The INTERNAL list exists for one reason: keeping internal artifacts off the
# public internet. In the private repos documentation belongs IN git, so there
# only the SECRET list applies -- otherwise the guard blocks the very docs it
# is supposed to preserve. Unlisted repos get the full check (fail-safe), so
# CI on a public repo and any new repo stay strict.
PRIVATE_REPOS='vault|opt-scripts|ai-plugin|ha-automations'

scope() {  # -> "all" | "secrets"
  [ -n "${LEAK_GUARD_SCOPE:-}" ] && { printf '%s\n' "$LEAK_GUARD_SCOPE"; return; }
  local url name
  url="$(git remote get-url origin 2>/dev/null)" || url=''
  name="$(basename "${url%.git}")"
  case "$name" in
    ?*) printf '%s\n' "$name" | grep -qxE "$PRIVATE_REPOS" \
           && echo secrets || echo all ;;
    *)  echo all ;;
  esac
}
SCOPE="$(scope)"

scan() {  # reads paths on stdin, prints "CLASS<TAB>path"
  # grep, not awk: awk -v strips the backslashes out of an ERE, which both warns
  # on every run and silently loosens the patterns (\.env$ would become .env$).
  local paths
  paths="$(grep -ivE "$ALLOW_RE")" || true
  [ -n "$paths" ] || return 0
  printf '%s\n' "$paths" | grep -iE "$SECRET_RE" | sed 's/^/SECRET\t/' || true
  [ "$SCOPE" = secrets ] && return 0
  printf '%s\n' "$paths" | grep -iE "$INTERNAL_RE" | grep -ivE "$SECRET_RE" \
    | sed 's/^/INTERNAL\t/' || true
}

mode="${1:-tree}"
case "$mode" in
  tree)
    ref="${2:-HEAD}"
    hits="$(git ls-tree -r --name-only "$ref" | scan)"
    where="tree at $ref"
    ;;
  range)
    [ $# -ge 3 ] || { echo "usage: leak-guard.sh range <base> <head>" >&2; exit 2; }
    # Every path introduced or touched anywhere in the range -- catches a file
    # added in one commit and deleted in the next, which a tip-only check misses.
    hits="$(git log --pretty=format: --name-only "$2..$3" -- | sort -u | sed '/^$/d' | scan)"
    where="commits $2..$3"
    ;;
  history)
    hits="$(git log --all --pretty=format: --name-only --diff-filter=A -- \
              | sort -u | sed '/^$/d' | scan)"
    where="full history (all refs)"
    ;;
  *) echo "usage: leak-guard.sh {tree [ref]|range <base> <head>|history}" >&2; exit 2 ;;
esac

note=''
[ "$SCOPE" = secrets ] && note=' (private repo: secrets only)'
[ -n "$hits" ] || { echo "Leak guard passed: nothing matched in $where$note."; exit 0; }

echo "LEAK GUARD FAILED -- disallowed paths in $where$note:" >&2
echo "$hits" | sort -u | sed 's/^/  /' >&2
echo >&2
echo "SECRET   = credential material. Untrack it AND rotate the credential." >&2
echo "INTERNAL = internal/auto-generated docs. Untrack and add to .gitignore." >&2
echo "Untrack: git rm --cached <path>   (deliberate override: git push --no-verify)" >&2
exit 1
